apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: laravel-basic-dotenv-dev
  namespace: openfaas-fn
spec:
  encryptedData:
    dotenv: YOUR-ENCRYPTED-DATA-HERE
  template:
    metadata:
      creationTimestamp: null
      name: laravel-basic-dotenv-dev
      namespace: openfaas-fn
status: {}
